### ISSUE TITLE
Give me edit access to this repo please

### ISSUE THREAD

**Issue by cassiemc** [mozilla/foxlight#29]
@simonwex? Someone? Suspect @hannahkane will need this too if she doesn't have it already to assign issues etc.

**Comment by hannahkane** [comment]
yes please and thank you

**Comment by gvn** [comment]
I'd like admin access as well. I can't reach the `settings` view.

**Comment by simonwex** [comment]
Done!

(I added mofo-admin-staffonly with admin access and mofo-staffonly with write access)

**Comment by gvn** [comment]
@simonwex I still can't reach the settings view. I'm assuming this is because I'm not part of the admin group?
